services:
  - type: web
    name: ocr-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000